"""Add column S3_URL in CommentMedia

Revision ID: 487a20334276
Revises: b86f618a31a7
Create Date: 2024-10-05 06:08:27.798027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487a20334276'
down_revision: Union[str, None] = 'b86f618a31a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments_media', sa.Column('s3_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'comments_media', ['s3_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments_media', type_='unique')
    op.drop_column('comments_media', 's3_url')
    # ### end Alembic commands ###
