"""empty message

Revision ID: 533464e9b1de
Revises: 487a20334276
Create Date: 2024-10-05 06:12:33.320680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533464e9b1de'
down_revision: Union[str, None] = '487a20334276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments_media', 's3_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments_media', 's3_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
