"""add coments

Revision ID: 4517dbf6bc67
Revises: 1a267a459d35
Create Date: 2024-09-14 20:01:47.028529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4517dbf6bc67'
down_revision: Union[str, None] = '1a267a459d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick', sa.String(length=15), nullable=True),
    sa.Column('text', sa.String(length=1500), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_thread_id'), 'comments', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
